AWSTemplateFormatVersion: 2010-09-09

Transform: AWS::Serverless-2016-10-31

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionUri: ./deploy/api.yaml
      StageName: prod
      Variables:
        LambdaFunctionName: !Ref ResizeFunction
  ResizeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist/function.zip
      Handler: index.handler
      Runtime: nodejs6.10
      MemorySize: 1536
      Timeout: 60
      Environment:
        Variables:
          BUCKET: brenda-dev-user-projects-in
          URL: http://brenda-dev-user-projects-in.s3-website-eu-west-1.amazonaws.com
      Policies:
          Statement:
            - Resource: arn:aws:s3:::brenda-dev-user-projects-in/*
              Effect: Allow
              Action:
                - s3:PutObject

  ResizeFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ResizeFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${Api}/*

  ImageBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: brenda-dev-user-projects-in
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Principal: "*"
            Resource: arn:aws:s3:::brenda-dev-user-projects-in/*

Outputs:
  BucketWebsiteUrl:
    Value: http://brenda-dev-user-projects-in.s3-website-eu-west-1.amazonaws.com
  Bucket:
    Value: brenda-dev-user-projects-in
  ApiHostName: !Sub ${Api}.execute-api.${AWS::Region}.amazonaws.com
